const PostActionTypes = {

    // fetch posts
    POST_FETCH_START: 'POST_FETCH_START',
    POST_FETCH_SUCCESS: 'POST_FETCH_SUCCESS',
    POST_FETCH_FAILURE: 'POST_FETCH_FAILURE',

    // fetch posts
    FETCH_NEWEST_POSTS_START: 'FETCH_NEWEST_POSTS_START',
    FETCH_NEWEST_POSTS_SUCCESS: 'FETCH_NEWEST_POSTS_SUCCESS',
    FETCH_NEWEST_POSTS_FAILURE: 'FETCH_NEWEST_POSTS_FAILURE',

    // create post
    POST_CREATE_START: 'POST_CREATE_START',
    POST_CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
    POST_CREATE_FAILURE: 'POST_CREATE_FAILURE',

    // update post
    POST_UPDATE_START: 'POST_UPDATE_START',
    POST_UPDATE_SUCCESS: 'POST_UPDATE_SUCCESS',
    POST_UPDATE_FAILURE: 'POST_UPDATE_FAILURE',

     // delete post
    POST_DELETE_START: 'POST_DELETE_START',
    POST_DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
    POST_DELETE_FAILURE: 'POST_DELETE_FAILURE',

    // like post
    POST_LIKE_START: 'POST_LIKE_START',
    POST_LIKE_SUCCESS: 'POST_LIKE_SUCCESS',
    POST_LIKE_FAILURE: 'POST_LIKE_FAILURE',

    // dislike post
    POST_DISLIKE_START: 'POST_DISLIKE_START',
    POST_DISLIKE_SUCCESS: 'POST_DISLIKE_SUCCESS',
    POST_DISLIKE_FAILURE: 'POST_DISLIKE_FAILURE',

    // retweet post
    POST_RETWEET_START: 'POST_RETWEET_START',
    POST_RETWEET_SUCCESS: 'POST_RETWEET_SUCCESS',
    POST_RETWEET_FAILURE: 'POST_RETWEET_FAILURE',
};
  
  export default PostActionTypes;
  