const PostActionTypes = {

    // fetch posts
    POST_FETCH_START: 'POST_FETCH_START',
    POST_FETCH_SUCCESS: 'POST_FETCH_SUCCESS',
    POST_FETCH_FAILURE: 'POST_FETCH_FAILURE',

    // create post
    POST_CREATE_START: 'POST_CREATE_START',
    POST_CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
    POST_CREATE_FAILURE: 'POST_CREATE_FAILURE',
    // update post
    POST_UPDATE_START: 'POST_UPDATE_START',
    POST_UPDATE_SUCCESS: 'POST_UPDATE_SUCCESS',
    POST_UPDATE_FAILURE: 'POST_UPDATE_FAILURE',
     // delete post
    POST_DELETE_START: 'POST_DELETE_START',
    POST_DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
    POST_DELETE_FAILURE: 'POST_DELETE_FAILURE'
  };
  
  export default PostActionTypes;
  