const UserActionTypes = {

  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  
  // sign in Google
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  // sign in
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  // sign in Wallet
  WALLET_SIGN_IN_START: 'WALLET_SIGN_IN_START',
  
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  // sign out user
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

  // sign up user
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  // update  user
  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  // fetch All Users
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

  // fetch All Users
  FETCH_USER_PROFILE_START: 'FETCH_USER_PROFILE_START',
  FETCH_USER_PROFILE_SUCCESS: 'FETCH_USER_PROFILE_SUCCESS',
  FETCH_USER_PROFILE_FAILURE: 'FETCH_USER_PROFILE_FAILURE',


// follow  users
  FOLLOW_START: 'FOLLOW_START',
  FOLLOW_SUCCESS: 'FOLLOW_SUCCESS',
  FOLLOW_FAILURE: 'FOLLOW_FAILURE',

  // follow  users
  UNFOLLOW_START: 'UNFOLLOW_START',
  UNFOLLOW_SUCCESS: 'UNFOLLOW_SUCCESS',
  UNFOLLOW_FAILURE: 'UNFOLLOW_FAILURE',

  // fetch follow users
  FETCH_FOLLOW_START: 'FETCH_FOLLOW_START',
  FETCH_FOLLOW_SUCCESS: 'FETCH_FOLLOW_SUCCESS',
  FETCH_FOLLOW_FAILURE: 'FETCH_FOLLOW_FAILURE',

  // fetch user posts
  FETCH_USER_POSTS_START: 'FETCH_USER_POSTS_START',
  FETCH_USER_POSTS_SUCCESS: 'FETCH_USER_POSTS_SUCCESS',
  FETCH_USER_POSTS_FAILURE: 'FETCH_USER_POSTS_FAILURE',

  // save post
  POST_SAVE_START: 'POST_SAVE_START',
  POST_SAVE_SUCCESS: 'POST_SAVE_SUCCESS',
  POST_SAVE_FAILURE: 'POST_SAVE_FAILURE',

  // save post
  POST_UNSAVE_START: 'POST_UNSAVE_START',
  POST_UNSAVE_SUCCESS: 'POST_UNSAVE_SUCCESS',
  POST_UNSAVE_FAILURE: 'POST_UNSAVE_FAILURE'
};

export default UserActionTypes;
